### ISSUE TITLE
predict_multireactant_mp.py error 

### ISSUE THREAD

**Issue by SejeongPark8354** [wenhao-gao/SynNet#11]
I run the code with my data (which have smiles data more than 2000). 
And then, the sentence like below was printed. 
Can you tell me why the error occurs? 
I don't know the exact list object which provoke the error. 

`list index out of range`

**Comment by rociomer** [comment]
We have addressed this and other issues in the new version of SynNet (thanks to @chrulm!). Closing this for now.
