### ISSUE TITLE
ZINC csv used by publication

### ISSUE THREAD

**Issue by linminhtoo** [wenhao-gao/SynNet#13]
hello wenhao & rocio,

I see that we have to provide `path/to/zinc.csv` to run the genetic algorithm (to replicate how it was done in the paper)
https://github.com/wenhao-gao/SynNet#synthesizable-molecular-design-1

```bash
optimize_ga.py -i path/to/zinc.csv --radius 2 --nbits 4096 --num_population 128 --num_offspring 512 --num_gen 200 --ncpu 32 --objective gsk
```

is it possible to provide the exact `zinc.csv` that was used in the publication? 
```
Seeds are randomly sampled from the ZINC database (Sterling & Irwin, 2015)
```

**Comment by rociomer** [comment]
Hi, you can get this from the TDC by following the instructions in the link below:
https://tdcommons.ai/generation_tasks/molgen/#zinc
