### ISSUE TITLE
add docs on `compute_embedding.py` needed for inference

### ISSUE THREAD

**Issue by linminhtoo** [wenhao-gao/SynNet#14]
hello (again), 

sorry that I am raising multiple issues. just want to make it easier for everyone else to start using this awesome work.

i didn't a note about how one could compute molecular fingerprints / GNN embeddings for a dataset. only after some CTRL+F, i found that `scripts/compute_embedding.py` does it. 
https://github.com/wenhao-gao/SynNet/blob/master/scripts/compute_embedding.py

so, it would be a good idea to add this to the README. I believe we need to do this step before running any inference.

**Comment by chrulm** [comment]
Hey, 

Thanks for the comments!

We've addressed this issue in a fork and will merge it once its not a WIP anymore. In the meantime, feel free to check out https://github.com/chrulm/SynNet/blob/refactor-syntree-generation/INSTRUCTIONS.md and let us know what you think!

**Comment by linminhtoo** [comment]
Great! I will have a look when I have some time, probably this or next weekend. Good to see you're working on refactoring synnet which will definitely make it more accessible to researchers and practitioners alike. Just curious, are you under the Coley group?
